### ISSUE TITLE
[Bug report]: Cadastro realizado com e-mail inválido

### ISSUE THREAD

**Issue by oliveiraeverton** [heliohenriquehfilho/clientWise#1]
**Passos para Reproduzir**
Passo 1: Acesse a página de registro
Passo 2: Adicione um e-mail do tipo nome@host
Passo 3: Adicione a senha
Passo 4: Clique em "Registrar"

**Comportamento Esperado**
- Uma mensagem dizendo que o e-mail não é válido

**Comportamento Observado**
![image](https://github.com/user-attachments/assets/bf7d76d8-aa63-4013-bce8-4301a9df0bfc)

**Comment by oliveiraeverton** [comment]
![image](https://github.com/user-attachments/assets/41418897-c8cf-4427-a372-a035b9cc7c06)

### Comportamento Esperado
Recusar o cadastro.

**Comment by oliveiraeverton** [comment]
![image](https://github.com/user-attachments/assets/7caca713-a32b-464e-8479-9710f96b197f)
### Comportamento Esperado
Cadastro realizado

**Comment by oliveiraeverton** [comment]
![image](https://github.com/user-attachments/assets/1f3bc334-1efb-4b4f-9a15-22590b394b90)
### Comportamento Esperado
Cadastro realizado

### Comportamento Observado
Erro ao registrar usuário. Verifique as informações fornecidas.

### Melhorias
Não está claro o porquê do erro. Melhorar a mensagem de erro dizendo o motivo do erro. O problema foi a senha? O problema foi porque já existe uma conta de email cadastrada com esse email?

**Comment by heliohenriquehfilho** [comment]
Resolvido!!! Obrigado pelo feedback
