### ISSUE TITLE
[Bug Report]: Cadastro de cliente

### ISSUE THREAD

**Issue by oliveiraeverton** [heliohenriquehfilho/clientWise#2]
**Passos para Reproduzir**
Passo 1: Acesse a página de "Cadastro de cliente"
Passo 2: Adicionar todos os dados do cliente, mas com um nome igual a de algum cliente
Passo 3: Clique em "Cadastrar cliente"

**Comportamento Esperado**
- Cliente cadastrado

**Comportamento Observado**
![image](https://github.com/user-attachments/assets/53382e3c-6bb7-4bbf-a3c9-9042c87b978e)

**Justificativa**
- O nome do cliente não pode ser parâmetro para ser chave primária

**Comment by heliohenriquehfilho** [comment]
Resolvido. Agora é um id_unico que referencia o cliente.
