### ISSUE TITLE
[Melhorias]: Idade do cliente

### ISSUE THREAD

**Issue by oliveiraeverton** [heliohenriquehfilho/clientWise#3]
**Comportamento Esperado**
- No caso o valor é colocado pela pessoa que está cadastrando o cliente, a idade do cliente, mas o melhor seria colocar a data de nascimento do cliente, porque a idade dele muda ao passar dos dias e sem a informação da data de nascimento não saberemos a idade real do cliente depois de 1 ano, pois seria difícil lembrar de atualizar a idade de todos os clientes. 

**Comportamento Observado**
![image](https://github.com/user-attachments/assets/32fd771d-d121-4e52-8eae-2f27ae8cfe59)

**Comment by heliohenriquehfilho** [comment]
Resolvido, agora o input é a data de nascimento.
