### ISSUE TITLE
[Bug Report]: Gênero do cliente

### ISSUE THREAD

**Issue by oliveiraeverton** [heliohenriquehfilho/clientWise#4]
**Passos para Reproduzir**
Passo 1: Acesse a página de "Cadastro de cliente"
Passo 2: Clicar em "Gerenciador de Clientes"
Passo 3: Selecionar um cliente com gênero "none", ver a lista de clientes cadastrado na tabela

**Comportamento Esperado**
- Campo do gênero vazio ou "none"

**Comportamento Observado**
![image](https://github.com/user-attachments/assets/09d0e9e6-7016-47dd-9896-5214018b408f)

**Comment by heliohenriquehfilho** [comment]
Resolvido com a opção de "None" agora;
