### ISSUE TITLE
[Bug Report]: Preço de custo do produto

### ISSUE THREAD

**Issue by oliveiraeverton** [heliohenriquehfilho/clientWise#5]
**Passos para Reproduzir**
Passo 1: Acesse a página de "Gerenciador de produto"
Passo 2: Escolher um produto na lista
Passo 3: Adicionar no campo de "custo do produto" um valor de ponto flutuante

obs.: o teste falhou tanto para valores com vírgula quanto para valores com ponto

**Comportamento Esperado**
- Valor do produto inserido corretamente

**Comportamento Observado**
![image](https://github.com/user-attachments/assets/e3f93d7b-2e10-4012-9b59-527bbd457366)

**Comment by heliohenriquehfilho** [comment]
Resolvido, era questão de setar "step" para incremento do numero.
