### ISSUE TITLE
[Bug report]: Cadastro de cliente com espaços

### ISSUE THREAD

**Issue by oliveiraeverton** [heliohenriquehfilho/clientWise#6]
**Passos para Reproduzir**
Passo 1: Acesse a página de "Cadastro de cliente"
Passo 2: Adicionar espaços nos campos
Passo 3: Clique em "Cadastrar cliente"

**Comportamento Esperado**
- Cliente inválido / Vazio

**Comportamento Observado**
![image](https://github.com/user-attachments/assets/a28b2665-8e7b-4514-ba71-4891a38e10ad)

**Comment by heliohenriquehfilho** [comment]
Resolvido.
